### ISSUE TITLE
Task | Comparison functions

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/cma-server#109]
Comparison functions compare two or more variables returning a bool Point containing TRUE or FALSE.

 Function | Operator | Description
:-------:|:--------:|-------------
  Gt     |    >     | Greater than
  Ge     |    >=    | Greater than or equal to
  Eq     |    =     | Equal
  Le     |    <=    | Less than or equal to
  Lt     |    <     | Less than
  Ne     |    <>    | Not equal to

Example

`Point.A >= 0.5`

```yaml
fn Ge:
    input1: point real /App/Service/Point.A
    input2: const real 0.5
```
