### ISSUE TITLE
Back | Task | Input different options

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/cma-server#118]
# Same Point input with different options must have different behavior

For example we have number of inputs of the same Point but with different options.

```yaml
fn Debug:
  input1: point real '/AppTest/Point.Name' 
  input2: point real '/AppTest/Point.Name' default 0.0
  input3: point real '/AppTest/Point.Name' status ok
  input4: point real '/AppTest/Point.Name' status ok default 0.0
```
For now all those inputs are referenced to the same Point,
But because of different options gives different behavior, those inputs have to be referenced to the diffirent Point's with same point name.

- [x] FnIn have to implement hash() method, returns unique hash for identify the options set
